### ISSUE TITLE
Unable to determine user type at resolve time

### ISSUE THREAD

**Issue by AshPlunkett** [AllianceSoftware/django-csvpermissions#8]
You should be able to know which column your evaluator is running in so that you can perform runtime sanity checks to catch errors before a user might find them.

You know which your target model is, but if you have multiple permissions that run the same evaluator in the same row, you've got no clue which column/user type is which at resolve time.

**Comment by levic** [comment]
This functionality has been added in the 0.3 branch as part of commit https://github.com/AllianceSoftware/django-csvpermissions/commit/7f4a99084acad1352d0725812593fe2b95546c41
